forage.myagent.agent.model.kind=openai
forage.myagent.agent.log.requests=true
forage.myagent.agent.log.responses=true

# Model coordinatess
# forage.myagent.agent.model.name=qwen2.5:7b-instruct
# forage.myagent.agent.base.url=http://localhost:11434/v1
# forage.myagent.agent.api.key=EMPTY

# Needs to be updated with the correct model name, base URL, and API key
forage.myagent.agent.model.name=qwen3-14b
forage.myagent.agent.base.url=LLM_BASE_URL
forage.myagent.agent.api.key=LLM_API_KEY

# Memory settings
forage.myagent.agent.features=memory
forage.myagent.agent.memory.kind=message-window
forage.myagent.agent.memory.max.messages=20

# Assigned port to avoid conflicts with other systems
camel.server.port=8080
camel.server.enabled=true
camel.server.staticEnabled=true