#! /bin/bash
# set -x

BASE=$PROJECT_SOURCE
CURRENT=`head $BASE/tools/scripts/current`

# echo "rewind..."
echo -e "\033[33mrewind...\033[0m"
echo "step $(($CURRENT)) discarded."
step "$(($CURRENT-1))"