#! /bin/bash
# set -x

BASE=$PROJECT_SOURCE
LAB=$BASE/lab
TOOLS=$BASE/tools
FF=$TOOLS/solution/steps

# Return chapter details when no argument is passed (no chapter requested)
if [ ! "$1" ]; then
  STEP=$(< $TOOLS/scripts/current)
  echo -e "\033[33mCurrent step: $STEP [`grep '^'$STEP' ' $FF/titles.txt | cut -d' ' -f 2-`]\033[0m"
  exit
fi

# Check OpenShift connectivity before modifying any files
if ! oc whoami &>/dev/null; then
  LOGIN_USER="${DEVWORKSPACE_NAMESPACE%%-devspaces}"
  LOGIN_SERVER="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"
  echo ""
  echo -e "\033[33mWARNING: Not logged into OpenShift. Step was not executed."
  echo -e "Please log in first:"
  echo ""
  echo -e "  oc login -u ${LOGIN_USER} -p <password> ${LOGIN_SERVER}"
  echo -e "\033[0m"
  exit 1
fi

# Get first and last step IDs
cd $FF
FIRST=`ls -d */ | sort -n | cut -f1 -d'/' | head -n 1`
 LAST=`ls -d */ | sort -n | cut -f1 -d'/' | tail -n 1`
cd $OLDPWD

# Abort if chapter requested doesn't exist
if (($1 < $FIRST || $1 > $LAST)); then
  echo ABORTED! no step $1 available.
  exit
fi

NEXT=$1


# to ensure all hidden files & dirs are deleted (.camel) we need to change directory and return
if [ ! -d "$LAB" ]; then
  mkdir $LAB
fi
cd $LAB
# ls -A | xargs --no-run-if-empty rm -r
# ls -d */ 2>/dev/null | xargs --no-run-if-empty rm -r
find . -mindepth 1 -delete
cd $OLDPWD

# Copy chapter sources to lab directory
cp -rn $FF/$NEXT/* $LAB
echo -e "\033[33mstep $1 ready [`grep '^'$1' ' $FF/titles.txt | cut -d' ' -f 2-`]\033[0m"

echo "$1" > $TOOLS/scripts/current

# Resolve lab configuration
step-config $LAB

cd $LAB
