# Datasource
spring.datasource.url=jdbc:postgresql://postgres:5432/labdb
spring.datasource.driverClassName=org.postgresql.Driver

# Datasource credentials
spring.datasource.username=
spring.datasource.password=

# S3 access
camel.component.aws2-s3.accessKey=
camel.component.aws2-s3.secretKey=
camel.component.aws2-s3.uriEndpointOverride=

# S3 bucket
s3.bucket=

# Serve UI shopping portal on a
camel.server.port=8080
camel.server.enabled=true
camel.server.staticEnabled=true

# Customer support chat URL
support.url=
