# Assigned port to avoid conflicts with other systems
camel.server.port=8080
camel.server.enabled=true
camel.server.staticEnabled=true

# spring.datasource.url=jdbc:postgresql://localhost:5432/test
# spring.datasource.username=test
# spring.datasource.password=test
# spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://postgres:5432/labdb
spring.datasource.username=user1
spring.datasource.password=ezG4jBA4
spring.datasource.driverClassName=org.postgresql.Driver

# S3 credentials
camel.component.aws2-s3.accessKey=Vwd6LvfsLa8MksZwZ56G
camel.component.aws2-s3.secretKey=106dHbHIpYApxhHlTFmP6lO2kuhjvfmzP8txMMqI
camel.component.aws2-s3.uriEndpointOverride=https://s3-openshift-storage.apps.cluster-tsmhd.dynamic.redhatworkshops.io


# Rocket.Chat credentials
rocketchat.token=5s2cRyIb8tmK0Vsdqqtevqt3wVfq0HVb0JgBK-8g3PC
rocketchat.userid=ubNC8KnNJAYPkuvbq
