quarkus.log.category.dev.ai4j.openai4j.level=DEBUG
quarkus.log.category.io.vertx.core.level=ERROR

# # Assigned port to avoid conflicts with other systems
# camel.server.port=8060

# camel.server.enabled=true
# camel.server.staticEnabled=true

# llm.url=localhost:11434

# spring.datasource.url=jdbc:postgresql://localhost:5432/test
# spring.datasource.username=test
# spring.datasource.password=test
# spring.datasource.driverClassName=org.postgresql.Driver

# # S3 credentials
# camel.component.aws2-s3.accessKey=Vwd6LvfsLa8MksZwZ56G
# camel.component.aws2-s3.secretKey=106dHbHIpYApxhHlTFmP6lO2kuhjvfmzP8txMMqI
# camel.component.aws2-s3.uriEndpointOverride=https://s3-openshift-storage.apps.cluster-tsmhd.dynamic.redhatworkshops.io

# Assigned port to avoid conflicts with other systems
camel.server.port=8080
camel.server.enabled=true
camel.server.staticEnabled=true

# spring.datasource.url=jdbc:postgresql://localhost:5432/test
# spring.datasource.username=test
# spring.datasource.password=test
# spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://postgres:5432/labdb
spring.datasource.username=user1
spring.datasource.password=ezG4jBA4
spring.datasource.driverClassName=org.postgresql.Driver

# S3 credentials
camel.component.aws2-s3.accessKey=Vwd6LvfsLa8MksZwZ56G
camel.component.aws2-s3.secretKey=106dHbHIpYApxhHlTFmP6lO2kuhjvfmzP8txMMqI
camel.component.aws2-s3.uriEndpointOverride=https://s3-openshift-storage.apps.cluster-tsmhd.dynamic.redhatworkshops.io
