<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <Invoice>
            <InvoiceNumber>
                <xsl:value-of select="/X12_850/Header/BEG/BEG-03"/>
            </InvoiceNumber>
            <DateOfIssue>
                <xsl:value-of select="/X12_850/Header/BEG/BEG-05"/>
            </DateOfIssue>
            <Seller>
                <Name>
                    <xsl:value-of select="/X12_850/Header/N1Loop[1]/N1/N1-02"/>
                </Name>
                <Address>
                    <Street>
                        <xsl:value-of select="/X12_850/Header/N1Loop[1]/N3/N3-01"/>
                    </Street>
                    <City>
                        <xsl:value-of select="/X12_850/Header/N1Loop[1]/N4/N4-01"/>
                    </City>
                    <State>
                        <xsl:value-of select="/X12_850/Header/N1Loop[1]/N4/N4-02"/>
                    </State>
                    <PostalCode>
                        <xsl:value-of select="/X12_850/Header/N1Loop[1]/N4/N4-03"/>
                    </PostalCode>
                </Address>
                <TaxId>
                    <xsl:value-of select="/X12_850/Header/N1Loop[1]/N1/N1-04"/>
                </TaxId>
                <IBAN>
                    <xsl:value-of select="/X12_850/Header/N9Loop[1]/N9/N9-02"/>
                </IBAN>
            </Seller>
            <Client>
                <Name>
                    <xsl:value-of select="/X12_850/Header/N1Loop[2]/N1/N1-02"/>
                </Name>
                <Address>
                    <Street>
                        <xsl:value-of select="/X12_850/Header/N1Loop[2]/N3/N3-01"/>
                    </Street>
                    <City>
                        <xsl:value-of select="/X12_850/Header/N1Loop[2]/N4/N4-01"/>
                    </City>
                    <State>
                        <xsl:value-of select="/X12_850/Header/N1Loop[2]/N4/N4-02"/>
                    </State>
                    <PostalCode>
                        <xsl:value-of select="/X12_850/Header/N1Loop[2]/N4/N4-03"/>
                    </PostalCode>
                </Address>
                <TaxId>
                    <xsl:value-of select="/X12_850/Header/N1Loop[2]/N1/N1-04"/>
                </TaxId>
            </Client>
            <Items>
                <xsl:for-each select="/X12_850/PO1Loop">
                    <Item>
                        <Number>
                            <xsl:value-of select="PO1/PO1-01"/>
                        </Number>
                        <ProductID>
                            <xsl:value-of select="PIDLoop/PID/PID-07"/>
                        </ProductID>
                        <ProductID>
                            <xsl:value-of select="PO1/PO1-07"/>
                        </ProductID>
                        <Description>
                            <xsl:value-of select="PIDLoop/PID/PID-05"/>
                        </Description>
                        <Quantity>
                            <xsl:value-of select="PO1/PO1-02"/>
                        </Quantity>
                        <xsl:if test="PO1/PO1-03 = 'EA'">
                            <UnitOfMeasure>
                                <xsl:value-of select="'Each'"/>
                            </UnitOfMeasure>
                        </xsl:if>
                        <NetPrice>
                            <xsl:value-of select="PO1/PO1-04"/>
                        </NetPrice>
                        <NetWorth>
                            <xsl:value-of select="PO1/PO1-04 * PO1/PO1-02"/>
                        </NetWorth>
                        <VATPercentage>
                            <xsl:value-of select="10"/>
                        </VATPercentage>
                        <GrossWorth>
                            <xsl:value-of select="round(100*(PO1/PO1-04 * PO1/PO1-02 * .10 + (PO1/PO1-04 * PO1/PO1-02))) div 100"/>
                        </GrossWorth>
                    </Item>
                </xsl:for-each>
            </Items>
            <Summary>
                <VATPercentage>
                    <xsl:value-of select="10"/>
                </VATPercentage>
                <NetWorth>
                    <xsl:value-of select="format-number(/X12_850/AMT/AMT-02 div (1.1), '0.00')"/>
                </NetWorth>
                <VATAmount>
                    <xsl:value-of select="/X12_850/AMT/AMT-02 - number(format-number(/X12_850/AMT/AMT-02 div (1.1), '0.00'))"/>
                </VATAmount>
                <GrossWorth>
                    <xsl:value-of select="/X12_850/AMT/AMT-02"/>
                </GrossWorth>
            </Summary>
        </Invoice>
    </xsl:template>
</xsl:stylesheet>